bus_job:
    resource: "@AutobusBusBundle/Resources/config/routing/job.yml"
    prefix:   /job

bus_execution:
    resource: "@AutobusBusBundle/Resources/config/routing/execution.yml"
    prefix:   /execution
