services:
  Autobus\Bundle\BusBundle\Runner\RunnerChain: ~

  form.type.service:
    class: Autobus\Bundle\BusBundle\Form\JobType
    arguments: ['@Autobus\Bundle\BusBundle\Runner\RunnerChain']
    tags: ['form.type']

  bus.runner.helloworld:
    class: Autobus\Bundle\BusBundle\Runner\HelloWorldRunner
    arguments:
      - '@event_dispatcher'
    tags: ['bus.runner']

  bus.job.factory:
    class: Autobus\Bundle\BusBundle\Entity\JobFactory

  bus.form.job.factory:
    class: Autobus\Bundle\BusBundle\Form\JobTypeFactory

  bus.event_listener.start_execution:
    class: Autobus\Bundle\BusBundle\EventListener\StartExecutionSubscriber
    tags: ['kernel.event_subscriber']

  bus.event_listener.finish_execution:
    class: Autobus\Bundle\BusBundle\EventListener\FinishExecutionSubscriber
    arguments:
      - '@logger'
    tags: ['kernel.event_subscriber']

  bus.event_listener.runner_exception_handle:
    class: Autobus\Bundle\BusBundle\EventListener\RunnerExceptionHandleSubscriber
    tags: ['kernel.event_subscriber']

  bus.event_listener.secure_web_job:
      class: Autobus\Bundle\BusBundle\EventListener\SecureWebJobSubscriber
      arguments:
        - '@Autobus\Bundle\BusBundle\Security\SecurityChain'
      tags: ['kernel.event_subscriber']
