version: '3.1'

services:
  web:
    image: nginx
    depends_on:
      - php
    volumes:
        - ./docker/dev/nginx.conf:/etc/nginx/conf.d/default.conf
        - .:/app

  php:
    build:
      context: docker/dev
    depends_on:
      - database
    volumes:
      - .:/app
    working_dir: /app

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: autobus
      MYSQL_ROOT_PASSWORD: root
