bus:
    resource: "@AutobusBusBundle/Resources/config/routing.yml"
    prefix:   /

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: service_index
        permanent: true
