services:
  BusBundle\Security\SecurityChain: ~

  bus.security_strategy.basic_auth:
    class: BusBundle\Security\Strategy\BasicAuthStrategy
    tags: ['bus.security_strategy']

  bus.security_strategy.ip_white_list:
    class: BusBundle\Security\Strategy\IPWhiteListStrategy
    tags: ['bus.security_strategy']
