services:
  BusBundle\Service\ServiceChain: ~

  form.type.service:
    class: BusBundle\Form\ServiceType
    arguments: ['@BusBundle\Service\ServiceChain']
    tags: ['form.type']

  bus.service.helloworld:
    class: BusBundle\Service\HelloWorldService
    arguments:
      - '@event_dispatcher'
    tags: ['bus.service']

  bus.service.factory:
    class: BusBundle\Entity\ServiceFactory

  bus.form.service.factory:
    class: BusBundle\Form\ServiceTypeFactory

  bus.event_listener.start_service_call:
    class: BusBundle\EventListener\StartServiceCallSubscriber
    tags: ['kernel.event_subscriber']

  bus.event_listener.finish_service_call:
    class: BusBundle\EventListener\FinishServiceCallSubscriber
    arguments:
      - '@logger'
    tags: ['kernel.event_subscriber']

  bus.event_listener.bus_service_exception_handle:
    class: BusBundle\EventListener\BusServiceExceptionHandleSubscriber
    tags: ['kernel.event_subscriber']

  bus.event_listener.secure_webservice:
      class: BusBundle\EventListener\SecureWebServiceSubscriber
      arguments:
        - '@BusBundle\Security\SecurityChain'
      tags: ['kernel.event_subscriber']
