services:
    bus_sample.runner.helloworld:
        class: Autobus\Bundle\BusSampleBundle\Runner\HelloWorldRunner
        arguments:
          - '@event_dispatcher'
        tags:
          - { name: 'bus.runner', label: 'Hello world'}

    bus_sample.runner.users:
        class: Autobus\Bundle\BusSampleBundle\Runner\UserListRunner
        arguments:
          - '@event_dispatcher'
        tags:
          - { name: 'bus.runner', label: 'User list'}
