services:

    Autobus\Bundle\BusExportBundle\Converter\ConverterChain: ~

    bus_export.converter.json:
        class: Autobus\Bundle\BusExportBundle\Converter\JSONConverter
        arguments:
            - '@jms_serializer'
            - 'json'
        tags: ['bus_export.converter']
    bus_export.converter.xml:
        class: Autobus\Bundle\BusExportBundle\Converter\XMLConverter
        arguments:
            - '@jms_serializer'
            - 'xml'
        tags: ['bus_export.converter']

    bus_export.converter.yml:
        class: Autobus\Bundle\BusExportBundle\Converter\YMLConverter
        arguments:
            - '@jms_serializer'
            - 'yml'
        tags: ['bus_export.converter']
    bus_export.converter.csv:
        class: Autobus\Bundle\BusExportBundle\Converter\CSVConverter
        tags: ['bus_export.converter']
